name: Test push to jira

on:
  issues:
    types: [opened]

jobs:
  jira-create-issue-api:

    runs-on: ubuntu-latest

    steps:
    - name: create Jira issue if github issue appears
      run: |
        curl -o /dev/null --silent --request POST --url '${{ secrets.JIRA_URL }}/rest/api/2/issue' -H "Authorization: Basic ${{ secrets.JIRA_TOKEN }}" \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/json' --data '{
              "fields": {
                 "project":
                  {
                      "key": "AIT"
                  },
                  "summary": "Hey, You have new issue ${{ github.event.issue.number }} at github",
                  "description": "${{ github.event.issue.title }} , check here ${{ github.event.issue.html_url }}",
                  "assignee":{"name":"${{ secrets.ASSIGNEE }}"},
                  "issuetype": {
                      "name": "Task"
                  }
              }
            }'
      
